## Printing Statements

In [1]:
print("GDSC Silicon University")

GDSC Silicon University


In [5]:
x=3
# print(x)
# print("the value of x is ",x)
# print(f"the value of x is {x}")

the value of x is 3


## Input Statements

In [ ]:
x=int(input("Enter a value"))
# print(x)
type(x)

In [10]:
str1="hello world"
print(str1)

hello world


## Slicing

In [14]:
str1[0:6:2]

'hlo'

## List - A Data Structure

In [15]:
list1=[3,"string",34.0]
print(list1)

[3, 'string', 34.0]


## Function syntax in Python

In [18]:
def func_name(x):
    y=input("enter the value")
    print(y*x)
func_name(5)

enter the value@
@@@@@


## Conditional Statements(If-elif-else)

In [19]:
#conditional statements
x=int(input("Enter the value of x: "))
if(x>100):
    print("Greater than 100")
elif (x>50) and (x<99):
    print("greater than 50 less than 100")
else:
    print("less than 50")

Enter the value of x: 46
less than 50


## Numpy
### NumPy stands for Numerical Python. It is an open-source Python library used to perform 
### various mathematical and scientific tasks. It contains multi-dimensional arrays 
### and matrices, along with many high-level mathematical functions that operate on these arrays and matrices.

In [ ]:
# What is the difference between Python List and a Numpy Array?
# Python list can contain elements with different data types whereas Numpy Array elements are always homogeneous(same data types).
# NumPy arrays are faster and more compact than Python lists.

# Why NumPy Arrays are faster than Lists?
# NumPy Array uses fixed memory to store data and less memory than Python lists.

In [ ]:
!pip install numpy

In [21]:
import numpy as np
list1=[1,2,3,4]
arr1=np.array(list1,dtype=np.int64)
print(arr1)

[1 2 3 4]


In [22]:
type(arr1)

numpy.ndarray

In [23]:
list2=[[1,2],[3,4]]
arr2=np.array(list2,dtype=np.int64)
print(arr2)

[[1 2]
 [3 4]]


In [26]:
arr3=np.ones((1,1))
print(arr3)

[[1.]]


In [27]:
arr4=np.zeros((1,5))
print(arr4)

[[0. 0. 0. 0. 0.]]


In [28]:
arr5=np.full((1,4),7)
print(arr5)

[[7 7 7 7]]


In [31]:
arr6=np.random.randint(1,7)
print(arr6)

5


In [33]:
arr7=np.eye(2)
print(arr7)

[[1. 0.]
 [0. 1.]]


## Pandas
### Pandas is an open source Python Data Analysis (data manipulation,data cleaning, data visualization) Library.
### Current requirement is to convert the dataset into a preferred data format called DATAFRAME(a multidimensional table)

In [34]:
!pip install pandas

In [1]:
import pandas as pd
dictionary={
    'apples':[3,2,0,1],
    'oranges':[5,4,3,2]
}
# print(dictionary)
purchases=pd.DataFrame(dictionary)
print(purchases)
#here is an example of dataframe  

   apples  oranges
0       3        5
1       2        4
2       0        3
3       1        2


In [2]:
orders=pd.read_table('http://bit.ly/chiporders')
# read_table for reading data present in table format
# read_csv is used for reading data in csv format
print(orders)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]  